# Generated by Django 4.0.2 on 2022-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_kadeqoriyalar_postlar_muellifler'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Universitet', models.CharField(max_length=20)),
                ('Fakulte', models.CharField(max_length=20)),
                ('Ixtisas', models.CharField(max_length=20)),
                ('AD', models.CharField(max_length=20)),
                ('Soyad', models.CharField(max_length=20)),
                ('Number', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Kadeqoriyalar',
        ),
        migrations.RemoveField(
            model_name='postlar',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postlar',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Muellifler',
        ),
        migrations.DeleteModel(
            name='Postlar',
        ),
    ]
